spring:
  datasource:
    url: jdbc:postgresql://ec2-3-25-217-12.ap-southeast-2.compute.amazonaws.com:5432/deliveryapp
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

logging.level:
  root: info
  com.twopro.deliveryapp: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace

ai:
  openai:
    api:
      key: ${OPENAI_API_KEY}
      url: https://api.openai.com/v1/chat/completions